### ISSUE TITLE
White spaces are inserted into string tempalte during formatting

### ISSUE THREAD

**Issue by petertrr** [saveourtool/diktat#1423] opened 2022-07-05 12:16 UTC
## Describe the bug
```kotlin
val foo = 
"""|Test1Test.java:1:1: Avoid using default package
                    |Test1Test.java:3:6: Class name should be in PascalCase
                    |Test1Test.java:5:5: Variable name should be in lowerCamelCase
                    |Test1Test.java:7:1: File should end with trailing newline
                    |""".trimMargin()
```

![image](https://user-images.githubusercontent.com/23018090/177325065-8a91d653-724f-43a5-8085-17ab0bcecf06.png)

## Expected behavior
Content of string tempalte shouldn't be changed.

## Environment information
* diktat version: 1.2.1

**Comment by 0x6675636b796f75676974687562** [comment] 2022-08-15 15:46
@petertrr, I believe this is a duplicate of #1347.

**Comment by 0x6675636b796f75676974687562** [comment] 2022-08-15 15:51
Duplicate of #1347

**Closed** 2022-08-15 15:51 UTC
Labels: bug, autofix
